### ISSUE TITLE
add document about how to customize offset management in receiver-based dstream

### ISSUE THREAD

**Issue by CuriousVini** [Azure/spark-eventhubs#79]
Is there any documentation on how can we do offset management with 1.x apis?

**Comment by CodingCat** [comment]
what do you mean by offset management?

**Comment by CodingCat** [comment]
any update on this?

**Comment by CuriousVini** [comment]
I saw in the source code that there is a default OffsetStore used for storing offsets. It would be nice to add some documentation around it for 1.x apis.

**Comment by CodingCat** [comment]
sure, transformed this as an issue

**Comment by CuriousVini** [comment]
Thanks!

**Comment by sabeegrewal** [comment]
Hey CuriousVini, we no longer support receiver-based streams, so there's not going to be any effort to create documentation in that area. There will be completely re-written documentation for Direct Streams and Structured Streams soon (as well as support for per partition configuration of offsets, enqueue times, and max rates).
